name: ci

on:
  push:
    branches:
      - "lab3"
      
jobs:
  dockerupload:
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build ./app_python/myapp -t $DOCKERHUB_USERNAME/app_python:latest
      - name: Push Docker image to DockerHub
        run: |
          docker push $DOCKERHUB_USERNAME/app_python:latest    